### ISSUE TITLE
Compatibility with 1.8.x

### ISSUE THREAD

**Issue by NemoN** [cyrilcc/org.openhab.binding.rflink#1]
Is the plugin compatible with OpenHAB 1.8.x?

**Comment by cyrilcc** [comment]
Not sure about that.
It seems that 1.8 bindings work with OpenHAB 2.0, but I think that 2.0 bindings don't work with OpenHAB 1.8.
I'll give a try.

**Comment by vzorglub** [comment]
Did you try? And did it work?

**Comment by johnjore** [comment]
This binding will never work with OH1, as its built around things and channels, which don't exist in OH1.
Would require a bit of re-write to make binding work in OH1.
