### ISSUE TITLE
Strange temperature value

### ISSUE THREAD

**Issue by fab33** [cyrilcc/org.openhab.binding.rflink#19]
I have some strange temperature value. Debug give me : 
```
23:21:36.727 [DEBUG] [flink.connector.RfLinkSerialConnector] - <<< 20;48;Tunex;ID=D901;TEMP=0052;HUM=20;BAT=OK;
23:21:36.728 [DEBUG] [ng.rflink.handler.RfLinkBridgeHandler] - Message received: Raw data = 20;48;Tunex;ID=D901;TEMP=0052;HUM=20;BAT=OK;, Seq number = 72, Device name = Tunex, Device ID = D901, Temperature = 8.199999809265137, running against 2 listeners
23:21:36.729 [DEBUG] [.binding.rflink.handler.RfLinkHandler] - Message fom bridge rflink:bridge:usb0 from device [Tunex-D901], attempting to match Tunex-D901
```
result must be 8.2°C and not 8.199999809265137 !

**Comment by fab33** [comment]
ok it's here : https://github.com/cyrilcc/org.openhab.binding.rflink/blob/da48b4f33ee1e5178734609b19408cdc5c8f5052/src/main/java/org/openhab/binding/rflink/messages/RfLinkTemperatureMessage.java#L49
you can change 10.0f by 10.0d
And I'm not java expert but I think this function doesn't handle negative temperature properly.
my code (in JS) for handling negative temperatures : 
```
                case "TEMP": result.temp = parseInt(value[1], 16);
                  if ((result.temp & 0x8000) > 0) {  // temperature is an signed int16
                       result.temp = result.temp & 0x7FFF;
                       result.temp = 0-result.temp;
                  }
                  result.temp = result.temp / 10;

```

**Comment by johnjore** [comment]
Why not help everyone out and make the change yourself with a pull request?

**Comment by fab33** [comment]
I don't have an openhab dev environment and my java knowledge is quite basic. But I will try to setup dev environment next week.

**Comment by majherek** [comment]
I think I correct those two problems.
Please check.

**Comment by fab33** [comment]
thank you @majherek.
