### ISSUE TITLE
Any way to disable discovery?

### ISSUE THREAD

**Issue by realroywalker** [cyrilcc/org.openhab.binding.rflink#20]
I've just installed the binding and it's working great so far (just tested with Eurodomest switches).
However, I keep getting notifications in the inbox of paperui for new devices found (RTS) as the RFLink picks up other items in the neighborhood.

Is there any way to disable the continuous discovery new things via the binding once I've configured my devices?

**Comment by hExPY** [comment]
I also looking forward for this Feature.
I'll give it a try searching for it in the existing Code or implementing it.
