### ISSUE TITLE
Misleading documentation of RTS thing Device Id

### ISSUE THREAD

**Issue by numo68** [cyrilcc/org.openhab.binding.rflink#40]
The `ESH-INF/thing/rts.xml` documents the Device Id as

> Must contain the Protocol + Address + EPROM index (using '-' as separator). For instance : RTS-123ABC-1

I have four RTS blinds with addresses xxxxx1, xxxxx2, xxxxx3 and xxxxx4 paired at EEPROM locations 1, 2, 3 and 4. I did understand this as the EEPROM index where the device is paired so I parametrized `RTS-xxxxx1-1`, `RTS-xxxxx2-2` etc. With these ids the second blind was operating in reverse - going up for the generated `10;RTS;xxxxx2;2;DOWN;` command.

I just have the blinds so it might be different for other devices; I think however that the final number is not an EEPROM index but a channel number inside the device. I thus configured the blind as `RTS-xxxxx2-1` and the direction now matches. 0 is fine as well. Just the 2 seems to invert.

I'd recommend to change the wording to something like "... + the channel number", possibly with further explanation that the blinds use a 1.

Thanks

**Comment by cartemere** [comment]
I checked the RFLink documentation... and it seems you are right ^^
[http://www.rflink.nl/blog2/protref](url)
> 10;RTS;1a602a;0;ON; => RTS protocol, address, command (zero is unused for now)

I will update the documentation according to your recommendation.
Thanks for the tip 👍

**Comment by cartemere** [comment]
configuration updated to reflect the changes
