### ISSUE TITLE
Is there a precompiled jar file that I can download?

### ISSUE THREAD

**Issue by 2delarosa** [cyrilcc/org.openhab.binding.rflink#5]
Hi,

I would like to use your binding but I'm not familiar with how to get it integrated with Openhab2.  The openhab forum does not provide much help.  It does state that one can manually add add-ons by placing jar files in /usr/share/openhab2/addons.  I looked are your files but I can't find the jar file.  Can you point me to where I can get more information on using your binding in my openhab installation.

**Comment by cyrilcc** [comment]
Hi,

Unfortunately, there is no jar, since this project is just a development purpose starting point for a rflink addon. And only a few devices are implemented.

**Comment by johnjore** [comment]
You can find a development copy here: 

https://www.dropbox.com/s/n1tfm9asi9btpgg/org.openhab.binding.rflink_2.0.0.jar?dl=0

The jar file is a work in progress, and may disappear at any time, it may also be broken as I'm in the process of adding support for a few devices I have.

As @cyrilcc stated above, not many device types are supported at this point in time so it may be useless.

**Comment by cyrilcc** [comment]
Thank you @johnjore for sharing 👍
