### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by MichaBrans** [cyrilcc/org.openhab.binding.rflink#6]
Hi,
Are there any plans to complete this binding in the near future?
Just started with RFLink & OpenHAB and would lilke to use a real binding, however if there are no plans to have a functional binding soon, I will go for one of the MQTT with python script options

Not wanting to push you, just want to know the plans ;-)

Thanks

**Comment by cyrilcc** [comment]
Hi, 
Sorry for the delay :/
The answer to your question is no, sorry. This project was just a starting point for developers interested in this topic.
BR.
